### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by GHXST01** [Magisk-Modules-Repo/MagiskHide-Props-Config#2]
Not sure where to ask this but I am repeatedly getting "Installation failed" when installing from zip or through the Magisk modules interface on my Moto G5 running Android 7.0

**Comment by Didgeridoohan** [comment]
Like it says in the [documentation](https://github.com/Magisk-Modules-Repo/MagiskHide-Props-Config#issues-support-etc), the [module support thread](https://forum.xda-developers.com/apps/magisk/module-magiskhide-props-config-t3789228) would have been a good place...

Since you've got a Moto device, you're probably affected by this:
https://www.didgeridoohan.com/magisk/Magisk#hn_Issues_with_f2fs
